### ISSUE TITLE
fix ImmutableList serialization 

### ISSUE THREAD

**Issue by QaysAyad** [enspyrco/the_process#42]
I found that the way that serialization for ImmutableList is basically doing noting and found that JsonSerializable do stuff automatically if you add a factory constructor like so:

`factory ImmutableList.fromJson(List<T> json) => ImmutableList.fromList(json);
`

**Comment by nickmeinhold** [comment]
Thanks @QaysAyad!  I jumped on your branch and ran the tests locally and they all pass (not that there are many tests and there are none related to serialising yet). 

I'm going to add some tests and do some json_serializable learning before merging but will get that done ASAP... thanks heaps!
